inherit_gem:
  rubocop-github:
    - config/default_edge.yml
    - config/rails_edge.yml
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'

Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/Documentation:
  Enabled: false
GitHub/RailsControllerRenderActionSymbol:
  Enabled: false
GitHub/RailsControllerRenderPathsExist:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Naming/VariableNumber:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'